### ISSUE TITLE
Missing column names in parsed BLAST text file for R

### ISSUE THREAD

**Issue by keegk** [keegk/Extraction_experiment#1]
When parsed BLAST text files (BLAST using blast7.sh script) for each extraction method are loaded into R, barcode 2,5 and 7 have missing column headers (sscinames qacc sacc pident length mismatch gapopen qstart qend sstart send evalue bitscore staxids). Bug believed to be with parse_v1_1.R script where the column names don't get incorporated into parsed text file if the first read had no hits. 

Scripts used for parsing blast text files:
parse_v1_1.R and parse.sh

Blast text files for using as input for the parse.sh script are here: /mnt/shared/projects/jhi/bioss/kkeegan_onttestdata/Extraction_experiment/super_accuracy_BLAST_missing_sequence_length (note that these need to be reBLASTed with query sequence length and subject sequence length included. You will also find the parse.sh and parse_v1_1.R script in this directory)

**Comment by nickschurch** [comment]
I'm taking a look at this now, but first we need a quick chat about versions and github. There are now:

- a copy of the `parse.R` script in the [Seal_MinION github repository](https://github.com/keegk/Seal_MinION/tree/main)
- a copy here (now listed as `parse_v1_1.sh`)
- three copies in the `Seal_MinION_analysis` data directory on the cluster (names `parse.R`, `parse_v1_1.R` & `parse_v1_2.R`), none of which are under version control
- two copies in the `Extraction_experiment` data directory on the cluster (names `parse.R`, `parse_v1_1.R`), neither of which is under version control

This is exactly the situation that version control is designed to prevent. 

There should be one repository with one copy of this script (and the other scripts you write), under version control, that  is then used by different projects. Project specific scripts or configurations can be stored in repositories for each project. No scripts should **ever** be in non-version-controlled directories. This also means that we don't need filenames to contain any kind of version information (we use a version string in the script itself only so we can identify from log files, which version of the code produces a log file we're looking at).

So this is the structure I suggest:

- Main code repository
  - scripts like parse.R
- Project 1
  - scripts like parse.sh that have project specific settings and paths that call parse.R
- Project 2
...etc

Since the script was developed under the Seal_MinION repo and it's history is there, I suggest renaming this repo so something non-project specific (something like "Environmental Nanopore Analysis", or whatever you want - see settings for doing this), and then creating a new `Seal_Minion` repository for project specific settings. 

Make sure this repo has the latest versions from the scattered places, and it would also be worth taking the opportunity to rename scripts something a bit more sensible while doing this. what does `parse.R` actually parse?? Going through all your scripts and renaming them more descriptively (something like `parsefilter_blasttable.R`, for example) will help future-you, and others.

**Comment by keegk** [comment]
Hi Nick,

Working on this now – I think my issue is that I didn’t know how to use git on the cluster so I was just adding individual scripts as I went without push/pulling from my remote repo on GitHub. Just looking in to cloning/setting up repositories on the cluster and one question I have is do you use the GitHub HTTPS or the SSH web url for cloning? I see I need to set up a personal access token for using the HTTPS link which seems straightforward but wondering if the cluster prefers us to use a (more secure?) SSH url instead?

Cheers,
Karen


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by nickschurch** [comment]
I use (and would advise you to use) an ssh key. It's easy to generate one on the command line on the cluster and then all you need to do is copy that into your github ssh keys list and away you go. There should be clear instructions on the cluster help documentation, but if you are struggling I'd suggest asking the HPC slack - Iain with be able to assist.

**Comment by keegk** [comment]
Hi Nick,

All repositories have been updated with more explanatory names and cloned on gruffalo cluster.

For the extraction experiment (getting back on track for the original issue raised), the bash scripts and R script, which are now under version control, are here:

/mnt/shared/projects/jhi/bioss/kkeegan_onttestdata/Extraction_experiment/Extraction_experiment

Just to recap, you are debugging the (now renamed) parsefilter_blasttable.R so that each parsed blast text file generated has headings,  such as sscinames qacc sacc, etc. Barcodes 2,5 and 7 were missing these headers as there first read had no hits. 

The bash script for running parsefilter_blasttable.R is parse_into_R.sh.

The current input blast text files are: /mnt/shared/projects/jhi/bioss/kkeegan_onttestdata/Extraction_experiment/super_accuracy_BLAST_missing_sequence_length


Cheers,
Karen

**Comment by keegk** [comment]
Hi Nick,

Looks like the new edits to the parsefilter_blasttable.R script have resulted in funny formatting, with the parsed text file consisting of only one column. The headings have been added but each heading is now an individual row within this single column. All subsequent read info is also represented as individual rows within this one column.

**Comment by nickschurch** [comment]
Try it now (script v 1.2)

**Comment by keegk** [comment]
Almost, missing double quotes around *each* header title, so should be this ("subject.sci.names","query.acc","subject.acc","percent.identity","alignment.length","mismatches","gap.opens","q.start","q.end","s.start","s.end","evalue","bit.score","subject.tax.ids") but instead is this ("subject.sci.names,.query.acc,.subject.acc,.percent.identity,.alignment.length,.mismatches,.gap.opens,.subject.length,.query.length,.q.start,.q.end,.s.start,.s.end,.evalue,.bit.score,.subject.tax.ids"). So when I try read.table in R, using sep = "," it throws an error "more columns than column names"

Also you might notice the . in front of the header names now e.g .query.acc, .subject.acc.

**Comment by keegk** [comment]
Hi Nick, any more luck with the parsing script?

**Comment by nickschurch** [comment]
Fixed and pushed.
